### ISSUE TITLE
ios run with white blank screen.

### ISSUE THREAD

**Issue by kingctan** [879479119/Bilibili-React-Native#10]
I tried the ios, seems only white blank screen show out.
please check it, thanks.

**Comment by uu-z** [comment]
yep, because the ios version has not yet developed

**Comment by kingctan** [comment]
if any plan for ios version?

**Comment by uu-z** [comment]
We want to finish the android version first, then the ios

**Comment by kingctan** [comment]
can you please tell how to run on ios with your app or give any advice 
then I can try to fork and help push the ios version. ^_^
Thanks.

**Comment by 879479119** [comment]
That really helps if you can build ios version,but I even don't have a  Mac....     you can @ncysatnaf here ,he  works with mac, but maybe too busy to see the issue

**Comment by kingctan** [comment]
ok, @ncysatnaf ,can you give any advice for the first ios version' running normally? ^_^
I don't find the way that ios version goes out just a bland white screen when start.

**Comment by uu-z** [comment]
@kingctan what about your question ?  just run the ios should be no problem.
if want to develop ios you can look from the Container and Components folder.
then component naming can be similar as `***.universal.js` `***.android.js` `***.ios.js` 
If you can join in us that would be great ＼（＾ ＾）／
