### ISSUE TITLE
can't run now for some bugs.

### ISSUE THREAD

**Issue by kingctan** [879479119/Bilibili-React-Native#14]
1. searchScreen.js NEED rename to SearchScreen.js
2. two export default.
3. can'f find variable FETCH.

it seems you need do some base test before push to github. ^_^
any way, thanks for sharing code with githuber , we are following.....

**Comment by 879479119** [comment]
Thanks for your issue~    I have patched 1 and 3(since I didn't publish a new version on npm),but I cannot find where bug2 is,can you tell?
