### ISSUE TITLE
看来现在用双层ScrollView嵌套是最现实的方法了。。。

### ISSUE THREAD

**Issue by 879479119** [879479119/Bilibili-React-Native#2]
#### APP首页上面有一个折叠效果的组件，可以拿出手机来试一下，做安卓的同学说那是一个原生的组件CollapsingToolbarLayout，但是我现在还不会封装，想着就模拟一个类似功能的；上方的左右滑动跟随还算能做，但是折叠效果我用了很多种方法都失败了：

---

**尝试1：**我在scrollview的onscroll里面提交了一个事件“scroll”，由上方折叠组件接受“scroll”事件进行处理，但是这样的动画是真的卡得没办法看；

**尝试2：**还是类似的方法，只不过这次我让折叠组件穿了一个setState的回调函数给scroll，心想这样性能会高一点，然而并没有什么卵用；

**尝试3：**我看了一下手势控制的一块，发现有一个控制当前组件是否处理触摸事件的属性，心血来潮试了一下把两个scrollView放到一起，这样用原生的滑动的话，性能肯定不会差，我们只需要监听他的滚动方向变化就好了；试了一下发现那个属性行不通，每一次接受手势的还是外面的那个scrollview，不知道是不是我自己的问题，希望有心人去temp里面看看 再试一试。

**尝试4：**过了一会儿我又想了个办法，既然上面的方法行不通，那我就用类似的，判定滚动方向后，我就只需要渲染一次，将scrollview转换成静态的view，神不知鬼不觉吗，这个常识还在继续，有结果了我会在这里贴出来。

**总结：**
1.我费话有点多，写这个东西真的是把我坑死了，可能是思路不对。
2.要让组件重新渲染的消费是极高的，不要想着做一帧一帧的渲染了，行不通。
3.在onScroll事件中执行的事件越简单，频率就越高，如果执行重新渲染等高耗时的操作。会导致事件采集频率降低到一秒三次左右。

**Comment by 879479119** [comment]
@ncysatnaf    我踩的坑。。  你有什么思路没

**Comment by uu-z** [comment]
@879479119 
这个暂时还没看到有比较好的解决方案～  
我试试看，不行的话估，计要封装一下CollapsingToolbarLayout

**Comment by youhan26** [comment]
碰到双层嵌套ScrollView的问题，搜了一圈，目前子ScrollView是接受不了scroll事件，能做的就是监听父层scroll事件，然后enableScroll = false，按照滑动手势去给子控件手动移动，scrollView有个scrollTo方法。。。。不过想想就觉得效率很低啊。。。。。。。绝望，请问你们还有好方法木有

**Comment by HermitCarb** [comment]
@879479119 偶然翻到这里，看你说到

> 在onScroll事件中执行的事件越简单，频率就越高，如果执行重新渲染等高耗时的操作。会导致事件采集频率降低到一秒三次左右。

还不太明白你的问题，如果需要降低onScroll的执行次数，可以试试lodash的debounce,throttle这两个函数。

**Comment by est7** [comment]
这个问题现在有啥好的解决方案了没..

**Comment by changelime** [comment]
https://github.com/facebook/react-native/issues/8024
这个issue里有解决方案

**Comment by titianqx** [comment]
有解决方案了么  我添加了手势监控   双层scrollview的问题倒是解决了 但是 TouchableOpacity 的onpress事件会偶尔触发不了  很蛋疼  把PanResponder注释掉后  onPress问题解决了  双层scrollview问题又来了。。   有人有解决办法么  ps：个别机型会出现onpress偶尔失灵   模拟器没问题

**Comment by huhu-001** [comment]
very good

**Comment by shuo-hiwintech** [comment]
哎，2025年了，RN社区依旧没有最佳实践.................
