### ISSUE TITLE
Mac上运行报错

### ISSUE THREAD

**Issue by EleTeam** [879479119/Bilibili-React-Native#7]
运行以下命令后：npm install，react-native run-ios，编译成功了，但是xcode模拟器上报错如下：Application reactNative has not been registered. This is either due to a required() error during initialization or failure to call AppRegistry.registerComponent.

**Comment by 879479119** [comment]
你改了项目文件名或者package.json里面的名字吗     应该是项目名和AppRegistry里注册的名字不一样导致的
