### ISSUE TITLE
Bug:搜索历史超出显示范围

### ISSUE THREAD

**Issue by uu-z** [879479119/Bilibili-React-Native#8]
![screenshot_2016-08-15-21-26-15_com reactnative](https://cloud.githubusercontent.com/assets/12439992/17665702/1fb54b1a-632f-11e6-940b-1071e2683def.png)

@879479119 清除历史点不到了～～

**Comment by 879479119** [comment]
呃呃   忘了限制

**Comment by uu-z** [comment]
我们把issues用起来吧～

**Comment by 879479119** [comment]
总有一天  会让这里座无虚席 233

**Comment by uu-z** [comment]
6666

**Comment by 879479119** [comment]
原生的搜索框高度可以根据输入法框的高度调整，不知道我们能不能实现

**Comment by uu-z** [comment]
我觉得差不多就ok了~ _(:з」∠)_
