### ISSUE TITLE
how to add context menu to live page's toolbar.

### ISSUE THREAD

**Issue by kingctan** [879479119/Bilibili-React-Native#9]
how to add context menu to live page's toolbar.
like qq's message page, the top right's plus button.
thanks.

**Comment by uu-z** [comment]
Look like  the Toolbar component of react native  can’t meet  you want., since It cannot be extended.
you can look here https://github.com/instea/react-native-popup-menu. 
also you can try make one. I'll be glad to help you.

**Comment by kingctan** [comment]
ok,thanks, i'll try and be here if have questions. ^_^
